// Code generated by jig; DO NOT EDIT.

//go:generate jig

package MergeAll

import (
	"fmt"
	"sync"
	"sync/atomic"

	"github.com/reactivego/scheduler"
	"github.com/reactivego/subscriber"
)

//jig:name Scheduler

// Scheduler is used to schedule tasks to support subscribing and observing.
type Scheduler scheduler.Scheduler

//jig:name Subscriber

// Subscriber is an alias for the subscriber.Subscriber interface type.
type Subscriber subscriber.Subscriber

// Subscription is an alias for the subscriber.Subscription interface type.
type Subscription subscriber.Subscription

// NewSubscriber creates a new subscriber.
func NewSubscriber() Subscriber {
	return subscriber.New()
}

//jig:name ObservableStringObserveFunc

// ObservableStringObserveFunc is the observer, a function that gets called whenever the
// observable has something to report. The next argument is the item value that
// is only valid when the done argument is false. When done is true and the err
// argument is not nil, then the observable has terminated with an error.
// When done is true and the err argument is nil, then the observable has
// completed normally.
type ObservableStringObserveFunc func(next ObservableString, err error, done bool)

//jig:name zeroObservableString

var zeroObservableString ObservableString

//jig:name ObservableObservableString

// ObservableObservableString is essentially a subscribe function taking an observe
// function, scheduler and an subscriber.
type ObservableObservableString func(ObservableStringObserveFunc, Scheduler, Subscriber)

//jig:name ObservableStringObserveFuncMethods

// Next is called by an ObservableObservableString to emit the next ObservableString value to the
// observer.
func (f ObservableStringObserveFunc) Next(next ObservableString) {
	f(next, nil, false)
}

// Error is called by an ObservableObservableString to report an error to the observer.
func (f ObservableStringObserveFunc) Error(err error) {
	f(zeroObservableString, err, true)
}

// Complete is called by an ObservableObservableString to signal that no more data is
// forthcoming to the observer.
func (f ObservableStringObserveFunc) Complete() {
	f(zeroObservableString, nil, true)
}

//jig:name ObservableStringObserver

// ObservableStringObserver is the interface used with CreateObservableString when implementing a custom
// observable.
type ObservableStringObserver interface {
	// Next emits the next ObservableString value.
	Next(ObservableString)
	// Error signals an error condition.
	Error(error)
	// Complete signals that no more data is to be expected.
	Complete()
	// Subscribed returns true when the subscription is currently valid.
	Subscribed() bool
}

//jig:name CreateObservableString

// CreateObservableString creates an Observable from scratch by calling observer methods
// programmatically.
func CreateObservableString(f func(ObservableStringObserver)) ObservableObservableString {
	observable := func(observe ObservableStringObserveFunc, scheduler Scheduler, subscriber Subscriber) {
		runner := scheduler.Schedule(func() {
			if !subscriber.Subscribed() {
				return
			}
			observer := func(next ObservableString, err error, done bool) {
				if subscriber.Subscribed() {
					observe(next, err, done)
				}
			}
			type ObserverSubscriber struct {
				ObservableStringObserveFunc
				Subscriber
			}
			f(&ObserverSubscriber{observer, subscriber})
		})
		subscriber.OnUnsubscribe(runner.Cancel)
	}
	return observable
}

//jig:name StringObserveFunc

// StringObserveFunc is the observer, a function that gets called whenever the
// observable has something to report. The next argument is the item value that
// is only valid when the done argument is false. When done is true and the err
// argument is not nil, then the observable has terminated with an error.
// When done is true and the err argument is nil, then the observable has
// completed normally.
type StringObserveFunc func(next string, err error, done bool)

//jig:name zeroString

var zeroString string

//jig:name ObservableString

// ObservableString is essentially a subscribe function taking an observe
// function, scheduler and an subscriber.
type ObservableString func(StringObserveFunc, Scheduler, Subscriber)

//jig:name JustString

// JustString creates an ObservableString that emits a particular item.
func JustString(element string) ObservableString {
	observable := func(observe StringObserveFunc, scheduler Scheduler, subscriber Subscriber) {
		done := false
		runner := scheduler.ScheduleRecursive(func(self func()) {
			if subscriber.Subscribed() {
				if !done {
					observe(element, nil, false)
					if subscriber.Subscribed() {
						done = true
						self()
					}
				} else {
					observe(zeroString, nil, true)
				}
			}
		})
		subscriber.OnUnsubscribe(runner.Cancel)
	}
	return observable
}

//jig:name ObservableObservableStringMergeAll

// MergeAll flattens a higher order observable by merging the observables it emits.
func (o ObservableObservableString) MergeAll() ObservableString {
	observable := func(observe StringObserveFunc, subscribeOn Scheduler, subscriber Subscriber) {
		var observers struct {
			sync.Mutex
			done	bool
			len	int32
		}
		observer := func(next string, err error, done bool) {
			observers.Lock()
			defer observers.Unlock()
			if !observers.done {
				switch {
				case !done:
					observe(next, nil, false)
				case err != nil:
					observers.done = true
					observe(zeroString, err, true)
				default:
					if atomic.AddInt32(&observers.len, -1) == 0 {
						observe(zeroString, nil, true)
					}
				}
			}
		}
		merger := func(next ObservableString, err error, done bool) {
			if !done {
				atomic.AddInt32(&observers.len, 1)
				next(observer, subscribeOn, subscriber)
			} else {
				observer(zeroString, err, true)
			}
		}
		subscribeOn.Schedule(func() {
			if !subscriber.Canceled() {
				observers.len = 1
				o(merger, subscribeOn, subscriber)
			}
		})
	}
	return observable
}

//jig:name Schedulers

func TrampolineScheduler() Scheduler	{ return scheduler.Trampoline }

func GoroutineScheduler() Scheduler	{ return scheduler.Goroutine }

//jig:name ObservableStringPrintln

// Println subscribes to the Observable and prints every item to os.Stdout
// while it waits for completion or error. Returns either the error or nil
// when the Observable completed normally.
// Println is performed on the Trampoline scheduler.
func (o ObservableString) Println() (err error) {
	subscriber := NewSubscriber()
	scheduler := TrampolineScheduler()
	observer := func(next string, e error, done bool) {
		if !done {
			fmt.Println(next)
		} else {
			err = e
			subscriber.Unsubscribe()
		}
	}
	subscriber.OnWait(scheduler.Wait)
	o(observer, scheduler, subscriber)
	subscriber.Wait()
	return
}
