// NOTE: This file was generated by rxgo. Do not modify.

// Package main implements ReactiveX extensions for Go.
package main

//go:generate $GOPATH/bin/rxgo main int --output=rx.go --map-types=MouseMove

import (
	"errors"
	"rxgo/filters"
	"rxgo/schedulers"
	"rxgo/unsubscriber"
	"sync"
	"time"
)

// ErrTimeout is delivered to an observer if the stream times out.
var ErrTimeout = errors.New("timeout")

// MaxReplaySize is the maximum size of a replay buffer. Can be modified.
var MaxReplaySize = 16384

type Scheduler schedulers.Scheduler

type Unsubscriber unsubscriber.Unsubscriber

// Subscribable is an interface returned as a result of calling
// the observable function. See e.g. type ObservableInt. Every
// observable is essentially a function taking an Observer (function)
// as parameter and returning a Subscribable (interface).
type Subscribable interface {
	SubscribeOn(scheduler Scheduler)
	Unsubscriber
}

type SubscribeOnFunc func(scheduler Scheduler)

func (s SubscribeOnFunc) SubscribeOn(scheduler Scheduler) {
	s(scheduler)
}

////////////////////////////////////////////////////////
// IntObserver
////////////////////////////////////////////////////////

type IntObserver interface {
	Next(int)
	Error(error)
	Complete()
	Unsubscriber
}

type IntObserverFunc func(int, error, bool)

var zeroInt int

func (f IntObserverFunc) Next(next int) {
	f(next, nil, false)
}

func (f IntObserverFunc) Error(err error) {
	f(zeroInt, err, false)
}

func (f IntObserverFunc) Complete() {
	f(zeroInt, nil, true)
}

////////////////////////////////////////////////////////
// ObservableInt
////////////////////////////////////////////////////////

type ObservableInt func(IntObserverFunc) Subscribable

/////////////////////////////////////////////////////////////////////////////
// FROM
/////////////////////////////////////////////////////////////////////////////

// CreateInt calls f(observer) to produce values for a stream of ints.
func CreateInt(f func(IntObserver)) ObservableInt {
	subscribe := func(observer IntObserverFunc) Subscribable {
		unsubscriber := new(unsubscriber.Int32)

		operation := func(next int, err error, completed bool) {
			if !unsubscriber.Unsubscribed() {
				observer(next, err, completed)
			}
		}

		subscribeOn := func(scheduler Scheduler) {
			scheduler.Schedule(func() {
				if !unsubscriber.Unsubscribed() {
					defer unsubscriber.Unsubscribe()
					observer := &struct {
						IntObserverFunc
						Unsubscriber
					}{operation, unsubscriber}
					f(observer)
				}
			})
		}

		return &struct {
			SubscribeOnFunc
			Unsubscriber
		}{subscribeOn, unsubscriber}
	}
	return subscribe
}

func EmptyInt() ObservableInt {
	return CreateInt(func(observer IntObserver) {
		observer.Complete()
	})
}

func NeverInt() ObservableInt {
	return CreateInt(func(observer IntObserver) {
	})
}

func ThrowInt(err error) ObservableInt {
	return CreateInt(func(observer IntObserver) {
		observer.Error(err)
	})
}

func FromIntArray(array []int) ObservableInt {
	return CreateInt(func(observer IntObserver) {
		for _, next := range array {
			if observer.Unsubscribed() {
				return
			}
			observer.Next(next)
		}
		observer.Complete()
	})
}

func FromInts(array ...int) ObservableInt {
	return FromIntArray(array)
}

func FromIntChannel(ch <-chan int) ObservableInt {
	return CreateInt(func(observer IntObserver) {
		for next := range ch {
			if observer.Unsubscribed() {
				return
			}
			observer.Next(next)
		}
		observer.Complete()
	})
}

func Interval(interval time.Duration) ObservableInt {
	return CreateInt(func(observer IntObserver) {
		i := 0
		for {
			time.Sleep(interval)
			if observer.Unsubscribed() {
				return
			}
			observer.Next(i)
			i++
		}
	})
}

func JustInt(element int) ObservableInt {
	return CreateInt(func(observer IntObserver) {
		observer.Next(element)
		observer.Complete()
	})
}

func Range(start, count int) ObservableInt {
	end := start + count
	return CreateInt(func(observer IntObserver) {
		for i := start; i < end; i++ {
			if observer.Unsubscribed() {
				return
			}
			observer.Next(i)
		}
		observer.Complete()
	})
}

// Repeat value count times.
func RepeatInt(value int, count int) ObservableInt {
	return CreateInt(func(observer IntObserver) {
		for i := 0; i < count; i++ {
			if observer.Unsubscribed() {
				return
			}
			observer.Next(value)
		}
		observer.Complete()
	})
}

// StartInt is designed to be used with functions that return a
// (int, error) tuple.
//
// If the error is non-nil the returned ObservableInt will be that error,
// otherwise it will be a single-value stream of int.
func StartInt(f func() (int, error)) ObservableInt {
	return CreateInt(func(observer IntObserver) {
		if next, err := f(); err != nil {
			observer.Error(err)
		} else {
			observer.Next(next)
			observer.Complete()
		}
	})
}

func MergeInt(observables ...ObservableInt) ObservableInt {
	if len(observables) == 0 {
		return EmptyInt()
	}
	return observables[0].Merge(observables[1:]...)
}

func MergeIntDelayError(observables ...ObservableInt) ObservableInt {
	if len(observables) == 0 {
		return EmptyInt()
	}
	return observables[0].MergeDelayError(observables[1:]...)
}

/////////////////////////////////////////////////////////////////////////////
// Subscribe
/////////////////////////////////////////////////////////////////////////////

func (s ObservableInt) SubscribeOn(scheduler Scheduler) ObservableInt {
	subscribe := func(observer IntObserverFunc) Subscribable {
		subscribable := s(observer)
		subscribable.SubscribeOn(scheduler)
		subscribeOn := func(scheduler Scheduler) {
			// ignore
		}
		return &struct {
			SubscribeOnFunc
			Unsubscriber
		}{subscribeOn, subscribable}
	}
	return subscribe
}

func (s ObservableInt) Subscribe(observer IntObserverFunc) Unsubscriber {
	subscribable := s(observer)
	subscribable.SubscribeOn(schedulers.GoroutineScheduler)
	// Only export Unsubscriber interface, not whole Subscribable.
	return &struct{ Unsubscriber }{subscribable}
}

func (s ObservableInt) SubscribeNext(f func(v int)) Unsubscriber {
	operator := func(next int, err error, completed bool) {
		if err == nil && !completed {
			f(next)
		}
	}
	return s.Subscribe(operator)
}

// Wait for completion of the stream and return any error.
func (s ObservableInt) Wait() error {
	doneChan := make(chan error)
	operator := func(next int, err error, completed bool) {
		if err != nil || completed {
			doneChan <- err
		}
	}
	s.Subscribe(operator)
	return <-doneChan
}

/////////////////////////////////////////////////////////////////////////////
// TO
/////////////////////////////////////////////////////////////////////////////

// ToOneWithError blocks until the stream emits exactly one value. Otherwise, it errors.
func (s ObservableInt) ToOneWithError() (v int, e error) {
	v = zeroInt
	errch := make(chan error, 1)
	s.One().Subscribe(func(next int, err error, completed bool) {
		if err != nil || completed {
			errch <- err
			// Close errch to make subsequent use of it panic. This will prevent
			// a coroutine inside an observable getting stuck on errch and leaking.
			close(errch)
		} else {
			v = next
		}
	})
	e = <-errch
	return
}

// ToOne blocks and returns the only value emitted by the stream, or the zero
// value if an error occurs.
func (s ObservableInt) ToOne() int {
	value, _ := s.ToOneWithError()
	return value
}

// ToArrayWithError collects all values from the stream into an array,
// returning it and any error.
func (s ObservableInt) ToArrayWithError() (a []int, e error) {
	a = []int{}
	errch := make(chan error, 1)
	s.Subscribe(func(next int, err error, completed bool) {
		if err != nil || completed {
			errch <- err
			// Close errch to make subsequent use of it panic. This will prevent
			// a coroutine inside an observable getting stuck on errch and leaking.
			close(errch)
		} else {
			a = append(a, next)
		}
	})
	e = <-errch
	return
}

// ToArray blocks and returns the values from the stream in an array.
func (s ObservableInt) ToArray() []int {
	out, _ := s.ToArrayWithError()
	return out
}

// ToChannelWithError returns next and error channels corresponding to the stream elements and
// any error. When the next channel closes, it may be either because of an error or
// because the observable completed. The next channel may be closed without having emitted any
// values. The error channel always emits a value to indicate the observable has finished.
// When the error channel emits nil then the observable completed without errors, otherwise
// the error channel emits the error. When the observable has finished both channels will be
// closed.
func (s ObservableInt) ToChannelWithError() (<-chan int, <-chan error) {
	nextch := make(chan int, 1)
	errch := make(chan error, 1)
	s.Subscribe(func(next int, err error, completed bool) {
		if err != nil || completed {
			errch <- err
			close(errch)
			close(nextch)
		} else {
			nextch <- next
		}
	})
	return nextch, errch
}

func (s ObservableInt) ToChannel() <-chan int {
	ch, _ := s.ToChannelWithError()
	return ch
}

/////////////////////////////////////////////////////////////////////////////
// FILTERS
/////////////////////////////////////////////////////////////////////////////

func (s ObservableInt) adaptFilter(filter filters.Filter) ObservableInt {
	subscribe := func(sink IntObserverFunc) Subscribable {
		genericToIntSink := func(next interface{}, err error, completed bool) {
			if nextInt, ok := next.(int); ok {
				sink(nextInt, err, completed)
			} else {
				sink(zeroInt, err, completed)
			}
		}
		genericToGenericFilter := filter(genericToIntSink)
		intToGenericSource := func(next int, err error, completed bool) {
			genericToGenericFilter(next, err, completed)
		}
		return s(intToGenericSource)
	}
	return subscribe
}

// Distinct removes duplicate elements in the stream.
func (s ObservableInt) Distinct() ObservableInt {
	return s.adaptFilter(filters.Distinct())
}

// ElementAt yields the Nth element of the stream.
func (s ObservableInt) ElementAt(n int) ObservableInt {
	return s.adaptFilter(filters.ElementAt(n))
}

// Filter elements in the stream on a function.
func (s ObservableInt) Filter(f func(int) bool) ObservableInt {
	predicate := func(v interface{}) bool {
		return f(v.(int))
	}
	return s.adaptFilter(filters.Where(predicate))
}

// Last returns just the first element of the stream.
func (s ObservableInt) First() ObservableInt {
	return s.adaptFilter(filters.First())
}

// Last returns just the last element of the stream.
func (s ObservableInt) Last() ObservableInt {
	return s.adaptFilter(filters.Last())
}

// SkipLast skips the first N elements of the stream.
func (s ObservableInt) Skip(n int) ObservableInt {
	return s.adaptFilter(filters.Skip(n))
}

// SkipLast skips the last N elements of the stream.
func (s ObservableInt) SkipLast(n int) ObservableInt {
	return s.adaptFilter(filters.SkipLast(n))
}

// Take returns just the first N elements of the stream.
func (s ObservableInt) Take(n int) ObservableInt {
	return s.adaptFilter(filters.Take(n))
}

// TakeLast returns just the last N elements of the stream.
func (s ObservableInt) TakeLast(n int) ObservableInt {
	return s.adaptFilter(filters.TakeLast(n))
}

// IgnoreElements ignores elements of the stream and emits only the completion events.
func (s ObservableInt) IgnoreElements() ObservableInt {
	return s.adaptFilter(filters.IgnoreElements())
}

// IgnoreCompletion ignores the completion event of the stream and therefore returns a stream that never completes.
func (s ObservableInt) IgnoreCompletion() ObservableInt {
	subscribe := func(observer IntObserverFunc) Subscribable {
		operator := func(next int, err error, completed bool) {
			if !completed {
				observer(next, err, completed)
			}
		}
		return s(operator)
	}
	return subscribe
}

func (s ObservableInt) One() ObservableInt {
	return s.adaptFilter(filters.One())
}

func (s ObservableInt) Replay(size int, duration time.Duration) ObservableInt {
	if size == 0 {
		size = MaxReplaySize
	}
	return s.adaptFilter(filters.Replay(size, duration))
}

func (s ObservableInt) Sample(duration time.Duration) ObservableInt {
	return s.adaptFilter(filters.Sample(duration))
}

// Debounce reduces subsequent duplicates to single items during a certain duration
func (s ObservableInt) Debounce(duration time.Duration) ObservableInt {
	return s.adaptFilter(filters.Debounce(duration))
}

/////////////////////////////////////////////////////////////////////////////
// COUNT
/////////////////////////////////////////////////////////////////////////////

func (s ObservableInt) Count() ObservableInt {
	subscribe := func(observer IntObserverFunc) Subscribable {
		count := 0
		operator := func(next int, err error, completed bool) {
			if err != nil || completed {
				observer(count, nil, false)
				observer(zeroInt, err, completed)
			}
			count++
		}
		return s(operator)
	}
	return subscribe
}

/////////////////////////////////////////////////////////////////////////////
// CONCAT
/////////////////////////////////////////////////////////////////////////////

func (s ObservableInt) Concat(other ...ObservableInt) ObservableInt {
	if len(other) == 0 {
		return s
	}
	subscribe := func(observer IntObserverFunc) Subscribable {
		unsubscribers := &unsubscriber.Collection{}

		var index int
		var maxIndex = 1 + len(other) - 1

		var wg sync.WaitGroup
		operator := func(next int, err error, completed bool) {
			switch {
			case err != nil:
				index = maxIndex
				observer.Error(err)
				wg.Done()
			case completed:
				if index == maxIndex {
					observer.Complete()
				}
				wg.Done()
			default:
				observer.Next(next)
			}
		}

		subscribeOn := func(scheduler Scheduler) {
			// Execute the first observable on the passed in scheduler.
			wg.Add(1)
			subscribable := s(operator)
			if !unsubscribers.Set(subscribable) {
				return
			}
			subscribable.SubscribeOn(scheduler)
			wg.Wait()

			for i, observable := range other {
				index = i + 1
				wg.Add(1)
				unsubscriber := observable.Subscribe(operator)
				if !unsubscribers.Set(unsubscriber) {
					return
				}
				wg.Wait()
				if index == maxIndex {
					return
				}
			}
		}

		return &struct {
			SubscribeOnFunc
			Unsubscriber
		}{subscribeOn, unsubscribers}
	}
	return subscribe
}

/////////////////////////////////////////////////////////////////////////////
// MERGE
/////////////////////////////////////////////////////////////////////////////

func (s ObservableInt) merge(other []ObservableInt, delayError bool) ObservableInt {
	if len(other) == 0 {
		return s
	}
	subscribe := func(observer IntObserverFunc) Subscribable {
		unsubscribers := &unsubscriber.Collection{}

		var (
			olock     sync.Mutex
			merged    int
			count     = 1 + len(other)
			lastError error
		)

		operator := func(next int, err error, completed bool) {
			// Only one observable can be forwarding at any one time.
			olock.Lock()
			defer olock.Unlock()

			if merged >= count {
				return
			}

			switch {
			case err != nil:
				if delayError {
					lastError = err
					merged++
				} else {
					observer.Error(err)
					merged = count
					// tell all still executing observables, we're no longer interested
					unsubscribers.Unsubscribe()
				}

			case completed:
				merged++
				if merged == count {
					if lastError != nil {
						observer.Error(lastError)
					} else {
						observer.Complete()
					}
				}
			default:
				observer.Next(next)
			}
		}

		subscribeOn := func(scheduler Scheduler) {
			subscribable := s(operator)
			if !unsubscribers.Add(subscribable) {
				return
			}
			subscribable.SubscribeOn(scheduler)
			for _, observable := range other {
				unsubscriber := observable.Subscribe(operator)
				if !unsubscribers.Add(unsubscriber) {
					return
				}
			}
		}

		return &struct {
			SubscribeOnFunc
			Unsubscriber
		}{subscribeOn, unsubscribers}
	}
	return subscribe
}

// Merge an arbitrary number of observables with this one.
// An error from any of the observables will terminate the merged stream.
func (s ObservableInt) Merge(other ...ObservableInt) ObservableInt {
	return s.merge(other, false)
}

// Merge an arbitrary number of observables with this one.
// Any error will be deferred until all observables terminate.
func (s ObservableInt) MergeDelayError(other ...ObservableInt) ObservableInt {
	return s.merge(other, true)
}

/////////////////////////////////////////////////////////////////////////////
// CATCH
/////////////////////////////////////////////////////////////////////////////

func (s ObservableInt) Catch(catch ObservableInt) ObservableInt {
	subscribe := func(observer IntObserverFunc) Subscribable {
		unsubscribers := &unsubscriber.Collection{}

		throwChan := make(chan error, 1)
		operator := func(next int, err error, completed bool) {
			switch {
			case err != nil:
				throwChan <- err
			case completed:
				observer.Complete()
				throwChan <- nil
			default:
				observer.Next(next)
			}
		}

		catcher := func() {
			if err := <-throwChan; err != nil {
				unsubscriber := catch.Subscribe(observer)
				if !unsubscribers.Set(unsubscriber) {
					return
				}
			}
		}

		subscribeOn := func(scheduler Scheduler) {
			go catcher()

			subscribable := s(operator)
			if !unsubscribers.Set(subscribable) {
				return
			}
			subscribable.SubscribeOn(scheduler)
		}

		unsubscribe := func() {
			throwChan <- nil
		}
		unsubscribers.OnUnsubscribe(unsubscribe)

		return &struct {
			SubscribeOnFunc
			Unsubscriber
		}{subscribeOn, unsubscribers}
	}
	return subscribe
}

/////////////////////////////////////////////////////////////////////////////
// RETRY
/////////////////////////////////////////////////////////////////////////////

func (s ObservableInt) Retry() ObservableInt {
	subscribe := func(observer IntObserverFunc) Subscribable {
		unsubscribers := &unsubscriber.Collection{}

		throwChan := make(chan error, 1)
		operator := func(next int, err error, completed bool) {
			switch {
			case err != nil:
				throwChan <- err
			case completed:
				observer.Complete()
				throwChan <- nil
			default:
				observer.Next(next)
			}
		}

		catcher := func(scheduler Scheduler) {
			for err := range throwChan {
				if err == nil {
					return
				}
				subscribable := s(operator)
				if !unsubscribers.Set(subscribable) {
					return
				}
				subscribable.SubscribeOn(scheduler)
			}
		}

		subscribeOn := func(scheduler Scheduler) {
			go catcher(scheduler)

			subscribable := s(operator)
			if !unsubscribers.Set(subscribable) {
				return
			}
			subscribable.SubscribeOn(scheduler)
		}

		unsubscribe := func() {
			throwChan <- nil
		}
		unsubscribers.OnUnsubscribe(unsubscribe)

		return &struct {
			SubscribeOnFunc
			Unsubscriber
		}{subscribeOn, unsubscribers}
	}
	return subscribe
}

/////////////////////////////////////////////////////////////////////////////
// DO
/////////////////////////////////////////////////////////////////////////////

// Do applies a function for each value passing through the stream.
func (s ObservableInt) Do(f func(next int)) ObservableInt {
	subscribe := func(observer IntObserverFunc) Subscribable {
		operator := func(next int, err error, completed bool) {
			if err == nil && !completed {
				f(next)
			}
			observer(next, err, completed)
		}
		return s(operator)
	}
	return subscribe
}

// DoOnError applies a function for any error on the stream.
func (s ObservableInt) DoOnError(f func(err error)) ObservableInt {
	subscribe := func(observer IntObserverFunc) Subscribable {
		operator := func(next int, err error, completed bool) {
			if err != nil {
				f(err)
			}
			observer(next, err, completed)
		}
		return s(operator)
	}
	return subscribe
}

// DoOnComplete applies a function when the stream completes.
func (s ObservableInt) DoOnComplete(f func()) ObservableInt {
	subscribe := func(observer IntObserverFunc) Subscribable {
		operator := func(next int, err error, completed bool) {
			if completed {
				f()
			}
			observer(next, err, completed)
		}
		return s(operator)
	}
	return subscribe
}

// Finally applies a function for any error or completion on the stream.
// This doesn't expose whether this was an error or a completion.
func (s ObservableInt) Finally(f func()) ObservableInt {
	subscribe := func(observer IntObserverFunc) Subscribable {
		operator := func(next int, err error, completed bool) {
			if err != nil || completed {
				f()
			}
			observer(next, err, completed)
		}
		return s(operator)
	}
	return subscribe
}

/////////////////////////////////////////////////////////////////////////////
// REDUCE
/////////////////////////////////////////////////////////////////////////////

func (s ObservableInt) Reduce(initial int, reducer func(int, int) int) ObservableInt {
	value := initial
	subscribe := func(observer IntObserverFunc) Subscribable {
		operator := func(next int, err error, completed bool) {
			if err != nil || completed {
				observer(value, nil, false)
				observer(zeroInt, err, completed)
			} else {
				value = reducer(value, next)
			}
		}
		return s(operator)
	}
	return subscribe
}

/////////////////////////////////////////////////////////////////////////////
// SCAN
/////////////////////////////////////////////////////////////////////////////

func (s ObservableInt) Scan(initial int, f func(int, int) int) ObservableInt {
	value := initial
	subscribe := func(observer IntObserverFunc) Subscribable {
		operator := func(next int, err error, completed bool) {
			if err != nil || completed {
				observer(zeroInt, err, completed)
			} else {
				value = f(value, next)
				observer(value, nil, false)
			}
		}
		return s(operator)
	}
	return subscribe
}

/////////////////////////////////////////////////////////////////////////////
// TIMEOUT
/////////////////////////////////////////////////////////////////////////////

func (s ObservableInt) Timeout(timeout time.Duration) ObservableInt {
	subscribe := func(observer IntObserverFunc) Subscribable {
		unsubscribers := &unsubscriber.Collection{}

		unsubchan := make(chan struct{})
		errchan := make(chan error)
		nextchan := make(chan int)
		deliver := func() {
			for {
				select {
				case <-unsubchan:
					return
				case <-time.After(timeout):
					observer(zeroInt, ErrTimeout, false)
					unsubscribers.Unsubscribe()
					return
				case err := <-errchan:
					observer(zeroInt, err, err == nil)
					unsubscribers.Unsubscribe()
					return
				case next := <-nextchan:
					observer(next, nil, false)
				}
			}
		}

		operator := func(next int, err error, completed bool) {
			if err != nil || completed {
				errchan <- err
			} else {
				nextchan <- next
			}
		}

		subscribeOn := func(scheduler Scheduler) {
			go deliver()

			subscribable := s(operator)
			if !unsubscribers.Set(subscribable) {
				return
			}
			subscribable.SubscribeOn(scheduler)
		}

		unsubscribe := func() {
			close(unsubchan)
		}
		unsubscribers.OnUnsubscribe(unsubscribe)

		return &struct {
			SubscribeOnFunc
			Unsubscriber
		}{subscribeOn, unsubscribers}
	}
	return subscribe
}

/////////////////////////////////////////////////////////////////////////////
// FORK
/////////////////////////////////////////////////////////////////////////////

// Fork replicates each event from the parent to every observer of the fork.
// This allows multiple subscriptions to a single observable.
func (s ObservableInt) Fork() ObservableInt {
	var observers struct {
		sync.Mutex
		items []IntObserverFunc
	}

	addObserver := func(observer IntObserverFunc) int {
		observers.Lock()
		defer observers.Unlock()
		index := len(observers.items)
		observers.items = append(observers.items, observer)
		return index
	}

	removeObserver := func(index int) {
		observers.Lock()
		defer observers.Unlock()
		observers.items[index] = nil
	}

	eachObserver := func(f func(observer IntObserverFunc)) {
		observers.Lock()
		defer observers.Unlock()
		for _, observer := range observers.items {
			if observer != nil {
				f(observer)
			}
		}
	}

	operator := func(next int, err error, completed bool) {
		eachObserver(func(observer IntObserverFunc) {
			observer(next, err, completed)
		})
	}

	subscribe := func(observer IntObserverFunc) Subscribable {
		unsubscribers := &unsubscriber.Collection{}
		index := addObserver(observer)

		subscribeOn := func(scheduler Scheduler) {
		}

		unsubscribe := func() {
			removeObserver(index)
		}
		unsubscribers.OnUnsubscribe(unsubscribe)

		return &struct {
			SubscribeOnFunc
			Unsubscriber
		}{subscribeOn, unsubscribers}
	}

	// Subscribes immediately on creation of the observable.
	// So before anybody actually subscribed.
	s.Subscribe(operator)

	return subscribe
}

/////////////////////////////////////////////////////////////////////////////
// PUBLISH
/////////////////////////////////////////////////////////////////////////////

type ConnectableInt struct {
	ObservableInt
	connect func() Unsubscriber
}

// Connect will subscribe to the parent observable to start receiving values.
// All values will then be passed on to the observers that subscribed to this
// connectable observable
func (s ConnectableInt) Connect() Unsubscriber {
	return s.connect()
}

// Publish creates a connectable observable that only starts emitting values
// after the Connect method is called on it.
func (s ObservableInt) Publish() ConnectableInt {
	var observers struct {
		sync.Mutex
		items []IntObserverFunc
	}

	addObserver := func(observer IntObserverFunc) int {
		observers.Lock()
		defer observers.Unlock()
		index := len(observers.items)
		observers.items = append(observers.items, observer)
		return index
	}

	removeObserver := func(index int) {
		observers.Lock()
		defer observers.Unlock()
		observers.items[index] = nil
	}

	eachObserver := func(f func(observer IntObserverFunc)) {
		observers.Lock()
		defer observers.Unlock()
		for _, observer := range observers.items {
			if observer != nil {
				f(observer)
			}
		}
	}

	operator := func(next int, err error, completed bool) {
		eachObserver(func(observer IntObserverFunc) {
			observer(next, err, completed)
		})
	}

	subscribe := func(observer IntObserverFunc) Subscribable {
		unsubscribers := &unsubscriber.Collection{}
		index := addObserver(observer)

		subscribeOn := func(scheduler Scheduler) {
		}

		unsubscribe := func() {
			removeObserver(index)
		}
		unsubscribers.OnUnsubscribe(unsubscribe)

		return &struct {
			SubscribeOnFunc
			Unsubscriber
		}{subscribeOn, unsubscribers}
	}

	// Connect our operator observer function to the source start receiving
	// values from the source and forward them to our subscribers.
	connect := func() Unsubscriber {
		return s.Subscribe(operator)
	}

	return ConnectableInt{ObservableInt: subscribe, connect: connect}
}

/////////////////////////////////////////////////////////////////////////////
// MATHEMATICAL
/////////////////////////////////////////////////////////////////////////////

func (s ObservableInt) Average() ObservableInt {
	var sum int
	var count int
	subscribe := func(observer IntObserverFunc) Subscribable {
		operator := func(next int, err error, completed bool) {
			if err != nil || completed {
				observer(sum/count, nil, false)
				observer(zeroInt, err, completed)
			} else {
				sum += next
				count++
			}
		}
		return s(operator)
	}
	return subscribe
}

func (s ObservableInt) Sum() ObservableInt {
	var sum int
	subscribe := func(observer IntObserverFunc) Subscribable {
		operator := func(next int, err error, completed bool) {
			if err != nil || completed {
				observer(sum, nil, false)
				observer(zeroInt, err, completed)
			} else {
				sum += next
			}
		}
		return s(operator)
	}
	return subscribe
}

func (s ObservableInt) Min() ObservableInt {
	started := false
	var min int
	subscribe := func(observer IntObserverFunc) Subscribable {
		operator := func(next int, err error, completed bool) {
			if err != nil || completed {
				if started {
					observer(min, nil, false)
				}
				observer(zeroInt, err, completed)
			} else {
				if started {
					if min > next {
						min = next
					}
				} else {
					min = next
					started = true
				}
			}
		}
		return s(operator)
	}
	return subscribe
}

func (s ObservableInt) Max() ObservableInt {
	started := false
	var max int
	subscribe := func(observer IntObserverFunc) Subscribable {
		operator := func(next int, err error, completed bool) {
			if err != nil || completed {
				if started {
					observer(max, nil, false)
				}
				observer(zeroInt, err, completed)
			} else {
				if started {
					if max < next {
						max = next
					}
				} else {
					max = next
					started = true
				}
			}
		}
		return s(operator)
	}
	return subscribe
}

/////////////////////////////////////////////////////////////////////////////
// MAP (int,MouseMove)
/////////////////////////////////////////////////////////////////////////////

func (s ObservableInt) MapMouseMove(f func(int) MouseMove) ObservableMouseMove {
	subscribe := func(observer MouseMoveObserverFunc) Subscribable {
		operator := func(next int, err error, completed bool) {
			var mapped MouseMove
			if err == nil && !completed {
				mapped = f(next)
			}
			observer(mapped, err, completed)
		}
		return s(operator)
	}
	return subscribe
}

/////////////////////////////////////////////////////////////////////////////
// FLATMAP (int,MouseMove)
/////////////////////////////////////////////////////////////////////////////

func (s ObservableInt) FlatMapMouseMove(f func(int) ObservableMouseMove) ObservableMouseMove {
	subscribe := func(observer MouseMoveObserverFunc) Subscribable {
		unsubscribers := &unsubscriber.Collection{}

		var wait struct {
			sync.Mutex
			Condition *sync.Cond
			Accum     int
		}
		wait.Condition = sync.NewCond(&wait.Mutex)

		waitForZero := func() bool {
			wait.Lock()
			defer wait.Unlock()
			for wait.Accum > 0 {
				wait.Condition.Wait()
			}
			return (wait.Accum == 0)
		}

		waitAdd := func() {
			wait.Lock()
			defer wait.Unlock()
			wait.Accum++
			wait.Condition.Broadcast()
		}

		waitDone := func() {
			wait.Lock()
			defer wait.Unlock()
			wait.Accum--
			wait.Condition.Broadcast()
		}

		waitCancel := func() {
			wait.Lock()
			defer wait.Unlock()
			wait.Accum = -1
			wait.Condition.Broadcast()
		}

		var lock sync.Mutex
		flatten := func(next MouseMove, err error, completed bool) {
			lock.Lock()
			defer lock.Unlock()
			// Finally
			if err != nil || completed {
				waitDone()
			}
			// IgnoreCompletion
			if !completed {
				observer(next, err, completed)
			}
		}

		operator := func(next int, err error, completed bool) {
			if err != nil || completed {
				if waitForZero() {
					observer(zeroMouseMove, err, err == nil)
				}
			} else {
				waitAdd()
				unsubscriber := f(next).Subscribe(flatten)
				if !unsubscribers.Add(unsubscriber) {
					return
				}

			}
		}

		subscribeOn := func(scheduler Scheduler) {
			subscribable := s(operator)
			if !unsubscribers.Add(subscribable) {
				return
			}
			subscribable.SubscribeOn(scheduler)
		}

		unsubscribe := func() {
			waitCancel()
		}
		unsubscribers.OnUnsubscribe(unsubscribe)

		return &struct {
			SubscribeOnFunc
			Unsubscriber
		}{subscribeOn, unsubscribers}
	}
	return subscribe
}

////////////////////////////////////////////////////////
// MouseMoveObserver
////////////////////////////////////////////////////////

type MouseMoveObserver interface {
	Next(MouseMove)
	Error(error)
	Complete()
	Unsubscriber
}

type MouseMoveObserverFunc func(MouseMove, error, bool)

var zeroMouseMove MouseMove

func (f MouseMoveObserverFunc) Next(next MouseMove) {
	f(next, nil, false)
}

func (f MouseMoveObserverFunc) Error(err error) {
	f(zeroMouseMove, err, false)
}

func (f MouseMoveObserverFunc) Complete() {
	f(zeroMouseMove, nil, true)
}

////////////////////////////////////////////////////////
// ObservableMouseMove
////////////////////////////////////////////////////////

type ObservableMouseMove func(MouseMoveObserverFunc) Subscribable

/////////////////////////////////////////////////////////////////////////////
// FROM
/////////////////////////////////////////////////////////////////////////////

// CreateMouseMove calls f(observer) to produce values for a stream of ints.
func CreateMouseMove(f func(MouseMoveObserver)) ObservableMouseMove {
	subscribe := func(observer MouseMoveObserverFunc) Subscribable {
		unsubscriber := new(unsubscriber.Int32)

		operation := func(next MouseMove, err error, completed bool) {
			if !unsubscriber.Unsubscribed() {
				observer(next, err, completed)
			}
		}

		subscribeOn := func(scheduler Scheduler) {
			scheduler.Schedule(func() {
				if !unsubscriber.Unsubscribed() {
					defer unsubscriber.Unsubscribe()
					observer := &struct {
						MouseMoveObserverFunc
						Unsubscriber
					}{operation, unsubscriber}
					f(observer)
				}
			})
		}

		return &struct {
			SubscribeOnFunc
			Unsubscriber
		}{subscribeOn, unsubscriber}
	}
	return subscribe
}

func EmptyMouseMove() ObservableMouseMove {
	return CreateMouseMove(func(observer MouseMoveObserver) {
		observer.Complete()
	})
}

func NeverMouseMove() ObservableMouseMove {
	return CreateMouseMove(func(observer MouseMoveObserver) {
	})
}

func ThrowMouseMove(err error) ObservableMouseMove {
	return CreateMouseMove(func(observer MouseMoveObserver) {
		observer.Error(err)
	})
}

func FromMouseMoveArray(array []MouseMove) ObservableMouseMove {
	return CreateMouseMove(func(observer MouseMoveObserver) {
		for _, next := range array {
			if observer.Unsubscribed() {
				return
			}
			observer.Next(next)
		}
		observer.Complete()
	})
}

func FromMouseMoves(array ...MouseMove) ObservableMouseMove {
	return FromMouseMoveArray(array)
}

func FromMouseMoveChannel(ch <-chan MouseMove) ObservableMouseMove {
	return CreateMouseMove(func(observer MouseMoveObserver) {
		for next := range ch {
			if observer.Unsubscribed() {
				return
			}
			observer.Next(next)
		}
		observer.Complete()
	})
}

func JustMouseMove(element MouseMove) ObservableMouseMove {
	return CreateMouseMove(func(observer MouseMoveObserver) {
		observer.Next(element)
		observer.Complete()
	})
}

// Repeat value count times.
func RepeatMouseMove(value MouseMove, count int) ObservableMouseMove {
	return CreateMouseMove(func(observer MouseMoveObserver) {
		for i := 0; i < count; i++ {
			if observer.Unsubscribed() {
				return
			}
			observer.Next(value)
		}
		observer.Complete()
	})
}

// StartMouseMove is designed to be used with functions that return a
// (MouseMove, error) tuple.
//
// If the error is non-nil the returned ObservableMouseMove will be that error,
// otherwise it will be a single-value stream of MouseMove.
func StartMouseMove(f func() (MouseMove, error)) ObservableMouseMove {
	return CreateMouseMove(func(observer MouseMoveObserver) {
		if next, err := f(); err != nil {
			observer.Error(err)
		} else {
			observer.Next(next)
			observer.Complete()
		}
	})
}

func MergeMouseMove(observables ...ObservableMouseMove) ObservableMouseMove {
	if len(observables) == 0 {
		return EmptyMouseMove()
	}
	return observables[0].Merge(observables[1:]...)
}

func MergeMouseMoveDelayError(observables ...ObservableMouseMove) ObservableMouseMove {
	if len(observables) == 0 {
		return EmptyMouseMove()
	}
	return observables[0].MergeDelayError(observables[1:]...)
}

/////////////////////////////////////////////////////////////////////////////
// Subscribe
/////////////////////////////////////////////////////////////////////////////

func (s ObservableMouseMove) SubscribeOn(scheduler Scheduler) ObservableMouseMove {
	subscribe := func(observer MouseMoveObserverFunc) Subscribable {
		subscribable := s(observer)
		subscribable.SubscribeOn(scheduler)
		subscribeOn := func(scheduler Scheduler) {
			// ignore
		}
		return &struct {
			SubscribeOnFunc
			Unsubscriber
		}{subscribeOn, subscribable}
	}
	return subscribe
}

func (s ObservableMouseMove) Subscribe(observer MouseMoveObserverFunc) Unsubscriber {
	subscribable := s(observer)
	subscribable.SubscribeOn(schedulers.GoroutineScheduler)
	// Only export Unsubscriber interface, not whole Subscribable.
	return &struct{ Unsubscriber }{subscribable}
}

func (s ObservableMouseMove) SubscribeNext(f func(v MouseMove)) Unsubscriber {
	operator := func(next MouseMove, err error, completed bool) {
		if err == nil && !completed {
			f(next)
		}
	}
	return s.Subscribe(operator)
}

// Wait for completion of the stream and return any error.
func (s ObservableMouseMove) Wait() error {
	doneChan := make(chan error)
	operator := func(next MouseMove, err error, completed bool) {
		if err != nil || completed {
			doneChan <- err
		}
	}
	s.Subscribe(operator)
	return <-doneChan
}

/////////////////////////////////////////////////////////////////////////////
// TO
/////////////////////////////////////////////////////////////////////////////

// ToOneWithError blocks until the stream emits exactly one value. Otherwise, it errors.
func (s ObservableMouseMove) ToOneWithError() (v MouseMove, e error) {
	v = zeroMouseMove
	errch := make(chan error, 1)
	s.One().Subscribe(func(next MouseMove, err error, completed bool) {
		if err != nil || completed {
			errch <- err
			// Close errch to make subsequent use of it panic. This will prevent
			// a coroutine inside an observable getting stuck on errch and leaking.
			close(errch)
		} else {
			v = next
		}
	})
	e = <-errch
	return
}

// ToOne blocks and returns the only value emitted by the stream, or the zero
// value if an error occurs.
func (s ObservableMouseMove) ToOne() MouseMove {
	value, _ := s.ToOneWithError()
	return value
}

// ToArrayWithError collects all values from the stream into an array,
// returning it and any error.
func (s ObservableMouseMove) ToArrayWithError() (a []MouseMove, e error) {
	a = []MouseMove{}
	errch := make(chan error, 1)
	s.Subscribe(func(next MouseMove, err error, completed bool) {
		if err != nil || completed {
			errch <- err
			// Close errch to make subsequent use of it panic. This will prevent
			// a coroutine inside an observable getting stuck on errch and leaking.
			close(errch)
		} else {
			a = append(a, next)
		}
	})
	e = <-errch
	return
}

// ToArray blocks and returns the values from the stream in an array.
func (s ObservableMouseMove) ToArray() []MouseMove {
	out, _ := s.ToArrayWithError()
	return out
}

// ToChannelWithError returns next and error channels corresponding to the stream elements and
// any error. When the next channel closes, it may be either because of an error or
// because the observable completed. The next channel may be closed without having emitted any
// values. The error channel always emits a value to indicate the observable has finished.
// When the error channel emits nil then the observable completed without errors, otherwise
// the error channel emits the error. When the observable has finished both channels will be
// closed.
func (s ObservableMouseMove) ToChannelWithError() (<-chan MouseMove, <-chan error) {
	nextch := make(chan MouseMove, 1)
	errch := make(chan error, 1)
	s.Subscribe(func(next MouseMove, err error, completed bool) {
		if err != nil || completed {
			errch <- err
			close(errch)
			close(nextch)
		} else {
			nextch <- next
		}
	})
	return nextch, errch
}

func (s ObservableMouseMove) ToChannel() <-chan MouseMove {
	ch, _ := s.ToChannelWithError()
	return ch
}

/////////////////////////////////////////////////////////////////////////////
// FILTERS
/////////////////////////////////////////////////////////////////////////////

func (s ObservableMouseMove) adaptFilter(filter filters.Filter) ObservableMouseMove {
	subscribe := func(sink MouseMoveObserverFunc) Subscribable {
		genericToMouseMoveSink := func(next interface{}, err error, completed bool) {
			if nextMouseMove, ok := next.(MouseMove); ok {
				sink(nextMouseMove, err, completed)
			} else {
				sink(zeroMouseMove, err, completed)
			}
		}
		genericToGenericFilter := filter(genericToMouseMoveSink)
		intToGenericSource := func(next MouseMove, err error, completed bool) {
			genericToGenericFilter(next, err, completed)
		}
		return s(intToGenericSource)
	}
	return subscribe
}

// Distinct removes duplicate elements in the stream.
func (s ObservableMouseMove) Distinct() ObservableMouseMove {
	return s.adaptFilter(filters.Distinct())
}

// ElementAt yields the Nth element of the stream.
func (s ObservableMouseMove) ElementAt(n int) ObservableMouseMove {
	return s.adaptFilter(filters.ElementAt(n))
}

// Filter elements in the stream on a function.
func (s ObservableMouseMove) Filter(f func(MouseMove) bool) ObservableMouseMove {
	predicate := func(v interface{}) bool {
		return f(v.(MouseMove))
	}
	return s.adaptFilter(filters.Where(predicate))
}

// Last returns just the first element of the stream.
func (s ObservableMouseMove) First() ObservableMouseMove {
	return s.adaptFilter(filters.First())
}

// Last returns just the last element of the stream.
func (s ObservableMouseMove) Last() ObservableMouseMove {
	return s.adaptFilter(filters.Last())
}

// SkipLast skips the first N elements of the stream.
func (s ObservableMouseMove) Skip(n int) ObservableMouseMove {
	return s.adaptFilter(filters.Skip(n))
}

// SkipLast skips the last N elements of the stream.
func (s ObservableMouseMove) SkipLast(n int) ObservableMouseMove {
	return s.adaptFilter(filters.SkipLast(n))
}

// Take returns just the first N elements of the stream.
func (s ObservableMouseMove) Take(n int) ObservableMouseMove {
	return s.adaptFilter(filters.Take(n))
}

// TakeLast returns just the last N elements of the stream.
func (s ObservableMouseMove) TakeLast(n int) ObservableMouseMove {
	return s.adaptFilter(filters.TakeLast(n))
}

// IgnoreElements ignores elements of the stream and emits only the completion events.
func (s ObservableMouseMove) IgnoreElements() ObservableMouseMove {
	return s.adaptFilter(filters.IgnoreElements())
}

// IgnoreCompletion ignores the completion event of the stream and therefore returns a stream that never completes.
func (s ObservableMouseMove) IgnoreCompletion() ObservableMouseMove {
	subscribe := func(observer MouseMoveObserverFunc) Subscribable {
		operator := func(next MouseMove, err error, completed bool) {
			if !completed {
				observer(next, err, completed)
			}
		}
		return s(operator)
	}
	return subscribe
}

func (s ObservableMouseMove) One() ObservableMouseMove {
	return s.adaptFilter(filters.One())
}

func (s ObservableMouseMove) Replay(size int, duration time.Duration) ObservableMouseMove {
	if size == 0 {
		size = MaxReplaySize
	}
	return s.adaptFilter(filters.Replay(size, duration))
}

func (s ObservableMouseMove) Sample(duration time.Duration) ObservableMouseMove {
	return s.adaptFilter(filters.Sample(duration))
}

// Debounce reduces subsequent duplicates to single items during a certain duration
func (s ObservableMouseMove) Debounce(duration time.Duration) ObservableMouseMove {
	return s.adaptFilter(filters.Debounce(duration))
}

/////////////////////////////////////////////////////////////////////////////
// COUNT
/////////////////////////////////////////////////////////////////////////////

func (s ObservableMouseMove) Count() ObservableInt {
	subscribe := func(observer IntObserverFunc) Subscribable {
		count := 0
		operator := func(next MouseMove, err error, completed bool) {
			if err != nil || completed {
				observer(count, nil, false)
				observer(zeroInt, err, completed)
			}
			count++
		}
		return s(operator)
	}
	return subscribe
}

/////////////////////////////////////////////////////////////////////////////
// CONCAT
/////////////////////////////////////////////////////////////////////////////

func (s ObservableMouseMove) Concat(other ...ObservableMouseMove) ObservableMouseMove {
	if len(other) == 0 {
		return s
	}
	subscribe := func(observer MouseMoveObserverFunc) Subscribable {
		unsubscribers := &unsubscriber.Collection{}

		var index int
		var maxIndex = 1 + len(other) - 1

		var wg sync.WaitGroup
		operator := func(next MouseMove, err error, completed bool) {
			switch {
			case err != nil:
				index = maxIndex
				observer.Error(err)
				wg.Done()
			case completed:
				if index == maxIndex {
					observer.Complete()
				}
				wg.Done()
			default:
				observer.Next(next)
			}
		}

		subscribeOn := func(scheduler Scheduler) {
			// Execute the first observable on the passed in scheduler.
			wg.Add(1)
			subscribable := s(operator)
			if !unsubscribers.Set(subscribable) {
				return
			}
			subscribable.SubscribeOn(scheduler)
			wg.Wait()

			for i, observable := range other {
				index = i + 1
				wg.Add(1)
				unsubscriber := observable.Subscribe(operator)
				if !unsubscribers.Set(unsubscriber) {
					return
				}
				wg.Wait()
				if index == maxIndex {
					return
				}
			}
		}

		return &struct {
			SubscribeOnFunc
			Unsubscriber
		}{subscribeOn, unsubscribers}
	}
	return subscribe
}

/////////////////////////////////////////////////////////////////////////////
// MERGE
/////////////////////////////////////////////////////////////////////////////

func (s ObservableMouseMove) merge(other []ObservableMouseMove, delayError bool) ObservableMouseMove {
	if len(other) == 0 {
		return s
	}
	subscribe := func(observer MouseMoveObserverFunc) Subscribable {
		unsubscribers := &unsubscriber.Collection{}

		var (
			olock     sync.Mutex
			merged    int
			count     = 1 + len(other)
			lastError error
		)

		operator := func(next MouseMove, err error, completed bool) {
			// Only one observable can be forwarding at any one time.
			olock.Lock()
			defer olock.Unlock()

			if merged >= count {
				return
			}

			switch {
			case err != nil:
				if delayError {
					lastError = err
					merged++
				} else {
					observer.Error(err)
					merged = count
					// tell all still executing observables, we're no longer interested
					unsubscribers.Unsubscribe()
				}

			case completed:
				merged++
				if merged == count {
					if lastError != nil {
						observer.Error(lastError)
					} else {
						observer.Complete()
					}
				}
			default:
				observer.Next(next)
			}
		}

		subscribeOn := func(scheduler Scheduler) {
			subscribable := s(operator)
			if !unsubscribers.Add(subscribable) {
				return
			}
			subscribable.SubscribeOn(scheduler)
			for _, observable := range other {
				unsubscriber := observable.Subscribe(operator)
				if !unsubscribers.Add(unsubscriber) {
					return
				}
			}
		}

		return &struct {
			SubscribeOnFunc
			Unsubscriber
		}{subscribeOn, unsubscribers}
	}
	return subscribe
}

// Merge an arbitrary number of observables with this one.
// An error from any of the observables will terminate the merged stream.
func (s ObservableMouseMove) Merge(other ...ObservableMouseMove) ObservableMouseMove {
	return s.merge(other, false)
}

// Merge an arbitrary number of observables with this one.
// Any error will be deferred until all observables terminate.
func (s ObservableMouseMove) MergeDelayError(other ...ObservableMouseMove) ObservableMouseMove {
	return s.merge(other, true)
}

/////////////////////////////////////////////////////////////////////////////
// CATCH
/////////////////////////////////////////////////////////////////////////////

func (s ObservableMouseMove) Catch(catch ObservableMouseMove) ObservableMouseMove {
	subscribe := func(observer MouseMoveObserverFunc) Subscribable {
		unsubscribers := &unsubscriber.Collection{}

		throwChan := make(chan error, 1)
		operator := func(next MouseMove, err error, completed bool) {
			switch {
			case err != nil:
				throwChan <- err
			case completed:
				observer.Complete()
				throwChan <- nil
			default:
				observer.Next(next)
			}
		}

		catcher := func() {
			if err := <-throwChan; err != nil {
				unsubscriber := catch.Subscribe(observer)
				if !unsubscribers.Set(unsubscriber) {
					return
				}
			}
		}

		subscribeOn := func(scheduler Scheduler) {
			go catcher()

			subscribable := s(operator)
			if !unsubscribers.Set(subscribable) {
				return
			}
			subscribable.SubscribeOn(scheduler)
		}

		unsubscribe := func() {
			throwChan <- nil
		}
		unsubscribers.OnUnsubscribe(unsubscribe)

		return &struct {
			SubscribeOnFunc
			Unsubscriber
		}{subscribeOn, unsubscribers}
	}
	return subscribe
}

/////////////////////////////////////////////////////////////////////////////
// RETRY
/////////////////////////////////////////////////////////////////////////////

func (s ObservableMouseMove) Retry() ObservableMouseMove {
	subscribe := func(observer MouseMoveObserverFunc) Subscribable {
		unsubscribers := &unsubscriber.Collection{}

		throwChan := make(chan error, 1)
		operator := func(next MouseMove, err error, completed bool) {
			switch {
			case err != nil:
				throwChan <- err
			case completed:
				observer.Complete()
				throwChan <- nil
			default:
				observer.Next(next)
			}
		}

		catcher := func(scheduler Scheduler) {
			for err := range throwChan {
				if err == nil {
					return
				}
				subscribable := s(operator)
				if !unsubscribers.Set(subscribable) {
					return
				}
				subscribable.SubscribeOn(scheduler)
			}
		}

		subscribeOn := func(scheduler Scheduler) {
			go catcher(scheduler)

			subscribable := s(operator)
			if !unsubscribers.Set(subscribable) {
				return
			}
			subscribable.SubscribeOn(scheduler)
		}

		unsubscribe := func() {
			throwChan <- nil
		}
		unsubscribers.OnUnsubscribe(unsubscribe)

		return &struct {
			SubscribeOnFunc
			Unsubscriber
		}{subscribeOn, unsubscribers}
	}
	return subscribe
}

/////////////////////////////////////////////////////////////////////////////
// DO
/////////////////////////////////////////////////////////////////////////////

// Do applies a function for each value passing through the stream.
func (s ObservableMouseMove) Do(f func(next MouseMove)) ObservableMouseMove {
	subscribe := func(observer MouseMoveObserverFunc) Subscribable {
		operator := func(next MouseMove, err error, completed bool) {
			if err == nil && !completed {
				f(next)
			}
			observer(next, err, completed)
		}
		return s(operator)
	}
	return subscribe
}

// DoOnError applies a function for any error on the stream.
func (s ObservableMouseMove) DoOnError(f func(err error)) ObservableMouseMove {
	subscribe := func(observer MouseMoveObserverFunc) Subscribable {
		operator := func(next MouseMove, err error, completed bool) {
			if err != nil {
				f(err)
			}
			observer(next, err, completed)
		}
		return s(operator)
	}
	return subscribe
}

// DoOnComplete applies a function when the stream completes.
func (s ObservableMouseMove) DoOnComplete(f func()) ObservableMouseMove {
	subscribe := func(observer MouseMoveObserverFunc) Subscribable {
		operator := func(next MouseMove, err error, completed bool) {
			if completed {
				f()
			}
			observer(next, err, completed)
		}
		return s(operator)
	}
	return subscribe
}

// Finally applies a function for any error or completion on the stream.
// This doesn't expose whether this was an error or a completion.
func (s ObservableMouseMove) Finally(f func()) ObservableMouseMove {
	subscribe := func(observer MouseMoveObserverFunc) Subscribable {
		operator := func(next MouseMove, err error, completed bool) {
			if err != nil || completed {
				f()
			}
			observer(next, err, completed)
		}
		return s(operator)
	}
	return subscribe
}

/////////////////////////////////////////////////////////////////////////////
// REDUCE
/////////////////////////////////////////////////////////////////////////////

func (s ObservableMouseMove) Reduce(initial MouseMove, reducer func(MouseMove, MouseMove) MouseMove) ObservableMouseMove {
	value := initial
	subscribe := func(observer MouseMoveObserverFunc) Subscribable {
		operator := func(next MouseMove, err error, completed bool) {
			if err != nil || completed {
				observer(value, nil, false)
				observer(zeroMouseMove, err, completed)
			} else {
				value = reducer(value, next)
			}
		}
		return s(operator)
	}
	return subscribe
}

/////////////////////////////////////////////////////////////////////////////
// SCAN
/////////////////////////////////////////////////////////////////////////////

func (s ObservableMouseMove) Scan(initial MouseMove, f func(MouseMove, MouseMove) MouseMove) ObservableMouseMove {
	value := initial
	subscribe := func(observer MouseMoveObserverFunc) Subscribable {
		operator := func(next MouseMove, err error, completed bool) {
			if err != nil || completed {
				observer(zeroMouseMove, err, completed)
			} else {
				value = f(value, next)
				observer(value, nil, false)
			}
		}
		return s(operator)
	}
	return subscribe
}

/////////////////////////////////////////////////////////////////////////////
// TIMEOUT
/////////////////////////////////////////////////////////////////////////////

func (s ObservableMouseMove) Timeout(timeout time.Duration) ObservableMouseMove {
	subscribe := func(observer MouseMoveObserverFunc) Subscribable {
		unsubscribers := &unsubscriber.Collection{}

		unsubchan := make(chan struct{})
		errchan := make(chan error)
		nextchan := make(chan MouseMove)
		deliver := func() {
			for {
				select {
				case <-unsubchan:
					return
				case <-time.After(timeout):
					observer(zeroMouseMove, ErrTimeout, false)
					unsubscribers.Unsubscribe()
					return
				case err := <-errchan:
					observer(zeroMouseMove, err, err == nil)
					unsubscribers.Unsubscribe()
					return
				case next := <-nextchan:
					observer(next, nil, false)
				}
			}
		}

		operator := func(next MouseMove, err error, completed bool) {
			if err != nil || completed {
				errchan <- err
			} else {
				nextchan <- next
			}
		}

		subscribeOn := func(scheduler Scheduler) {
			go deliver()

			subscribable := s(operator)
			if !unsubscribers.Set(subscribable) {
				return
			}
			subscribable.SubscribeOn(scheduler)
		}

		unsubscribe := func() {
			close(unsubchan)
		}
		unsubscribers.OnUnsubscribe(unsubscribe)

		return &struct {
			SubscribeOnFunc
			Unsubscriber
		}{subscribeOn, unsubscribers}
	}
	return subscribe
}

/////////////////////////////////////////////////////////////////////////////
// FORK
/////////////////////////////////////////////////////////////////////////////

// Fork replicates each event from the parent to every observer of the fork.
// This allows multiple subscriptions to a single observable.
func (s ObservableMouseMove) Fork() ObservableMouseMove {
	var observers struct {
		sync.Mutex
		items []MouseMoveObserverFunc
	}

	addObserver := func(observer MouseMoveObserverFunc) int {
		observers.Lock()
		defer observers.Unlock()
		index := len(observers.items)
		observers.items = append(observers.items, observer)
		return index
	}

	removeObserver := func(index int) {
		observers.Lock()
		defer observers.Unlock()
		observers.items[index] = nil
	}

	eachObserver := func(f func(observer MouseMoveObserverFunc)) {
		observers.Lock()
		defer observers.Unlock()
		for _, observer := range observers.items {
			if observer != nil {
				f(observer)
			}
		}
	}

	operator := func(next MouseMove, err error, completed bool) {
		eachObserver(func(observer MouseMoveObserverFunc) {
			observer(next, err, completed)
		})
	}

	subscribe := func(observer MouseMoveObserverFunc) Subscribable {
		unsubscribers := &unsubscriber.Collection{}
		index := addObserver(observer)

		subscribeOn := func(scheduler Scheduler) {
		}

		unsubscribe := func() {
			removeObserver(index)
		}
		unsubscribers.OnUnsubscribe(unsubscribe)

		return &struct {
			SubscribeOnFunc
			Unsubscriber
		}{subscribeOn, unsubscribers}
	}

	// Subscribes immediately on creation of the observable.
	// So before anybody actually subscribed.
	s.Subscribe(operator)

	return subscribe
}

/////////////////////////////////////////////////////////////////////////////
// PUBLISH
/////////////////////////////////////////////////////////////////////////////

type ConnectableMouseMove struct {
	ObservableMouseMove
	connect func() Unsubscriber
}

// Connect will subscribe to the parent observable to start receiving values.
// All values will then be passed on to the observers that subscribed to this
// connectable observable
func (s ConnectableMouseMove) Connect() Unsubscriber {
	return s.connect()
}

// Publish creates a connectable observable that only starts emitting values
// after the Connect method is called on it.
func (s ObservableMouseMove) Publish() ConnectableMouseMove {
	var observers struct {
		sync.Mutex
		items []MouseMoveObserverFunc
	}

	addObserver := func(observer MouseMoveObserverFunc) int {
		observers.Lock()
		defer observers.Unlock()
		index := len(observers.items)
		observers.items = append(observers.items, observer)
		return index
	}

	removeObserver := func(index int) {
		observers.Lock()
		defer observers.Unlock()
		observers.items[index] = nil
	}

	eachObserver := func(f func(observer MouseMoveObserverFunc)) {
		observers.Lock()
		defer observers.Unlock()
		for _, observer := range observers.items {
			if observer != nil {
				f(observer)
			}
		}
	}

	operator := func(next MouseMove, err error, completed bool) {
		eachObserver(func(observer MouseMoveObserverFunc) {
			observer(next, err, completed)
		})
	}

	subscribe := func(observer MouseMoveObserverFunc) Subscribable {
		unsubscribers := &unsubscriber.Collection{}
		index := addObserver(observer)

		subscribeOn := func(scheduler Scheduler) {
		}

		unsubscribe := func() {
			removeObserver(index)
		}
		unsubscribers.OnUnsubscribe(unsubscribe)

		return &struct {
			SubscribeOnFunc
			Unsubscriber
		}{subscribeOn, unsubscribers}
	}

	// Connect our operator observer function to the source start receiving
	// values from the source and forward them to our subscribers.
	connect := func() Unsubscriber {
		return s.Subscribe(operator)
	}

	return ConnectableMouseMove{ObservableMouseMove: subscribe, connect: connect}
}

/////////////////////////////////////////////////////////////////////////////
// MAP (MouseMove,MouseMove)
/////////////////////////////////////////////////////////////////////////////

func (s ObservableMouseMove) MapMouseMove(f func(MouseMove) MouseMove) ObservableMouseMove {
	subscribe := func(observer MouseMoveObserverFunc) Subscribable {
		operator := func(next MouseMove, err error, completed bool) {
			var mapped MouseMove
			if err == nil && !completed {
				mapped = f(next)
			}
			observer(mapped, err, completed)
		}
		return s(operator)
	}
	return subscribe
}

/////////////////////////////////////////////////////////////////////////////
// FLATMAP (MouseMove,MouseMove)
/////////////////////////////////////////////////////////////////////////////

func (s ObservableMouseMove) FlatMapMouseMove(f func(MouseMove) ObservableMouseMove) ObservableMouseMove {
	subscribe := func(observer MouseMoveObserverFunc) Subscribable {
		unsubscribers := &unsubscriber.Collection{}

		var wait struct {
			sync.Mutex
			Condition *sync.Cond
			Accum     int
		}
		wait.Condition = sync.NewCond(&wait.Mutex)

		waitForZero := func() bool {
			wait.Lock()
			defer wait.Unlock()
			for wait.Accum > 0 {
				wait.Condition.Wait()
			}
			return (wait.Accum == 0)
		}

		waitAdd := func() {
			wait.Lock()
			defer wait.Unlock()
			wait.Accum++
			wait.Condition.Broadcast()
		}

		waitDone := func() {
			wait.Lock()
			defer wait.Unlock()
			wait.Accum--
			wait.Condition.Broadcast()
		}

		waitCancel := func() {
			wait.Lock()
			defer wait.Unlock()
			wait.Accum = -1
			wait.Condition.Broadcast()
		}

		var lock sync.Mutex
		flatten := func(next MouseMove, err error, completed bool) {
			lock.Lock()
			defer lock.Unlock()
			// Finally
			if err != nil || completed {
				waitDone()
			}
			// IgnoreCompletion
			if !completed {
				observer(next, err, completed)
			}
		}

		operator := func(next MouseMove, err error, completed bool) {
			if err != nil || completed {
				if waitForZero() {
					observer(zeroMouseMove, err, err == nil)
				}
			} else {
				waitAdd()
				unsubscriber := f(next).Subscribe(flatten)
				if !unsubscribers.Add(unsubscriber) {
					return
				}

			}
		}

		subscribeOn := func(scheduler Scheduler) {
			subscribable := s(operator)
			if !unsubscribers.Add(subscribable) {
				return
			}
			subscribable.SubscribeOn(scheduler)
		}

		unsubscribe := func() {
			waitCancel()
		}
		unsubscribers.OnUnsubscribe(unsubscribe)

		return &struct {
			SubscribeOnFunc
			Unsubscriber
		}{subscribeOn, unsubscribers}
	}
	return subscribe
}
